name: first workflow push
on: [push]

jobs:
  build:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: Write a multi-line message
        run: |
          echo This demo file shows a 
          echo very basic and easy-to-understand workflow.
          ls -la